import { Geist, Geist_Mono } from "next/font/google";
import Link from 'next/link'
import LoginButton from '../app/login/LoginButton.jsx'
import SignOutButton from './signout/SignOutButton.jsx'
import UserDataHandler from '@/contexts/AuthContext'
import "./globals.css";
import 'leaflet/dist/leaflet.css';
import 'leaflet-draw/dist/leaflet.draw.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserDataHandler>
        <nav className="main-nav">
          <Link href="/">回首頁</Link>
          <Link href="/member">會員頁面</Link>
          <Link href="/posts">文章</Link>
          <Link href="/events">揪團頁面</Link>
          <LoginButton />
          <SignOutButton />
        </nav>
        <hr />
        {children}
      </UserDataHandler>
      </body>
    </html>
  );
}
