import React from 'react';
import { Geist, Geist_Mono as GeistMono } from 'next/font/google';
import Link from 'next/link';
import LoginButton from './login/LoginButton.jsx';
import SignOutButton from './signout/SignOutButton.jsx';
import UserDataHandler from '@/contexts/AuthContext';
import ToastProvider from '@/contexts/ToastContext';
import ToastContainer from '@/components/ToastContainer';
import './globals.css';
import 'leaflet/dist/leaflet.css';
import 'leaflet-draw/dist/leaflet.draw.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = GeistMono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * 應用程式根佈局，包含導覽列與全域 Provider。
 * @param {object} root0 - 元件屬性。
 * @param {React.ReactNode} root0.children - 子頁面內容。
 * @returns {React.JSX.Element} 根佈局元件。
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <UserDataHandler>
          <ToastProvider>
            <nav className="main-nav">
              <Link href="/">回首頁</Link>
              <Link href="/member">會員頁面</Link>
              <Link href="/posts">文章</Link>
              <Link href="/events">揪團頁面</Link>
              <Link href="/runs">跑步</Link>
              <LoginButton />
              <SignOutButton />
            </nav>
            <hr />
            {children}
            <ToastContainer />
          </ToastProvider>
        </UserDataHandler>
      </body>
    </html>
  );
}
